version: "3"

services:
  postgres:
    container_name: postgres_db_test_goland
    image: 'postgres'
    ports:
      - "12345:5432"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/

  gateway:
    container_name: gateway
    build:
      context: ./backend/gateway/
      dockerfile: Dockerfile
    ports:
      - "4001:4001"

networks:
  work-map:
    driver: bridge