services:
  gateway:
    container_name: gateway
    build:
      context: ./backend/gateway/
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    networks:
      - gateway

  gateway-redis:
    container_name: gateway-redis
    image: redis:alpine
    ports:
      - "6378:6379"
    env_file:
      - ./backend/gateway/.env
    entrypoint: [ "sh", "-c", "redis-server --requirepass $${REDIS_PASSWORD}" ]
    networks:
      - gateway


networks:
  work-map:
    driver: bridge
  gateway:
    driver: bridge