name: Pre-Deploy

on:
  pull_request:
    branches:
      - main
      - dev
  workflow_run:
    workflows: ["Auth", "Gateway"]
    types:
      - completed

jobs:
  pre-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.17.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose
        docker-compose --version    

    - name: Create .env file for auth service
      run: |
        echo "JWT_ACCESS_SECRET_KEY=${{ secrets.JWT_ACCESS_SECRET_KEY }}" >> ../../backend/auth/Auth.GRPC/.env
        echo "JWT_REFRESH_SECRET_KEY=${{ secrets.JWT_REFRESH_SECRET_KEY }}" >> ../../backend/auth/Auth.GRPC/.env
        echo "SERVICE_PORT=${{ vars.AUTH_SERVICE_PORT }}" >> ../../backend/auth/Auth.GRPC/.env
        echo "SERVICE_HOST=${{ vars.AUTH_SERVICE_HOST }}" >> ../../backend/auth/Auth.GRPC/.env
        echo "POSTGRES_PORT=${{ vars.AUTH_POSTGRES_PORT }}" >> ../../backend/auth/Auth.GRPC/.env
        echo "POSTGRES_HOST=${{ vars.AUTH_POSTGRES_HOST }}" >> ../../backend/auth/Auth.GRPC/.env
        echo "POSTGRES_DB=${{ secrets.AUTH_POSTGRES_DB }}" >> ../../backend/auth/Auth.GRPC/.env
        echo "POSTGRES_USER=${{ secrets.AUTH_POSTGRES_USER }}" >> ../../backend/auth/Auth.GRPC/.env
        echo "POSTGRES_PASSWORD=${{ secrets.AUTH_POSTGRES_PASSWORD }}" >> ../../backend/auth/Auth.GRPC/.env
        echo "REDIS_PORT=${{ vars.AUTH_REDIS_PORT }}" >> ../../backend/auth/Auth.GRPC/.env
        echo "REDIS_HOST=${{ vars.AUTH_REDIS_HOST }}" >> ../../backend/auth/Auth.GRPC/.env
        echo "REDIS_PASSWORD=${{ secrets.AUTH_REDIS_PASSWORD }}" >> ../../backend/auth/Auth.GRPC/.env

    - name: Create .env file for gateway
      run: |
        echo "PORT=${{ vars.GATEWAY_PORT }}" >> ../../backend/gateway/.env
        echo "AUTH_SERVICE_PORT=${{ vars.GATEWAY_AUTH_SERVICE_PORT }}" >> ../../backend/gateway/.env
        echo "REDIS_PORT=${{ vars.GATEWAY_REDIS_PORT}}" >> ../../backend/gateway/.env
        echo "REDIS_HOST=${{ vars.GATEWAY_REDIS_HOST }}" >> ../../backend/gateway/.env
        echo "REDIS_PASSWORD=${{ secrets.GATEWAY_REDIS_PASSWORD }}" >> ../../backend/gateway/.env

    - name: Docker Compose Up
      run: docker-compose up -d --build
      working-directory: ../../backend

    - name: Check Docker Container Status
      run: docker ps
      working-directory: ../../backend
